schema_version: 1
aliases:
  company_name:             .Library_General_Settings.Company_Name
  build_info:               .Library_General_Settings.Library_Version
  package_filename:         .Library_General_Settings.Package_File_Name
  description:              .Advanced_Settings.Description.Description
  display_icon:             .Library_General_Settings.Package_Icon
  dest_toolkit_vis:         .Advanced_Settings.Destinations.Toolkit_VIs
  dest_examples:            .Advanced_Settings.Destinations.Examples
  dest_custom_probes:       .Advanced_Settings.Destinations.Custom_Probes
  dest_custom_errors:       .Advanced_Settings.Destinations.Custom_Errors
  dest_help_files:          .Advanced_Settings.Destinations.Help_Files
  dest_template_vis:        .Advanced_Settings.Destinations.Template_VIs
  dest_file_menu:           .Advanced_Settings.Destinations.File_Menu
  dest_tools_menu:          .Advanced_Settings.Destinations.Tools_Menu
  dest_help_menu:           .Advanced_Settings.Destinations.Help_Menu
  dest_project_templates:   .Advanced_Settings.Destinations.Project_Templates
  dest_project_provider:    .Advanced_Settings.Destinations.Project_Provider
  dest_quickdrop_plugins:   .Advanced_Settings.Destinations.QuickDrop_Plugins
  dest_additional:          .Advanced_Settings.Destinations.Additional_Destination
  src_destination_overrides: .Advanced_Settings.Source_Files.Destination_Overrides
  src_password_overrides:    .Advanced_Settings.Source_Files.Password_Overrides
  src_namespace_overrides:   .Advanced_Settings.Source_Files.Namespace_Overrides
  src_exclusions:            .Advanced_Settings.Source_Files.Exclusions
  src_compile_exclusions:    .Advanced_Settings.Source_Files.Compile_Exclusions
  src_place_folder_contents: .Advanced_Settings.Source_Files.Place_Folder_Contents
  package_dependencies:      .Advanced_Settings.Package_Dependencies
  req_all_windows:           .Advanced_Settings.Install_Requirements.All_Windows
  req_windows_7:             .Advanced_Settings.Install_Requirements.Windows_7
  req_windows_vista:         .Advanced_Settings.Install_Requirements.Windows_Vista
  req_windows_xp:            .Advanced_Settings.Install_Requirements.Windows_XP
  req_windows_8:             .Advanced_Settings.Install_Requirements.Windows_8
  req_mac_os:                .Advanced_Settings.Install_Requirements.Mac_OS
  req_linux:                 .Advanced_Settings.Install_Requirements.Linux
  req_built_lv_version:      .Advanced_Settings.Install_Requirements.Built_LV_Version
  req_built_lv_or_greater:   .Advanced_Settings.Install_Requirements.Built_LV_Version_or_greater
  req_os_32bit:              .Advanced_Settings.Install_Requirements."OS_32-Bit"
  req_os_64bit:              .Advanced_Settings.Install_Requirements."OS_64-Bit"
  req_lv_32bit:              .Advanced_Settings.Install_Requirements."LV_32-Bit"
  req_lv_64bit:              .Advanced_Settings.Install_Requirements."LV_64-Bit"
  ca_pre_build_vi:           .Advanced_Settings.Custom_Action_VIs.Pre-Build_VI
  ca_post_build_vi:          .Advanced_Settings.Custom_Action_VIs.Post-Build_VI
  ca_pre_install_vi:         .Advanced_Settings.Custom_Action_VIs.Pre-Install_VI
  ca_post_install_vi:        .Advanced_Settings.Custom_Action_VIs.Post-Install_VI
  ca_pre_uninstall_vi:       .Advanced_Settings.Custom_Action_VIs.Pre-Uninstall_VI
  ca_post_uninstall_vi:      .Advanced_Settings.Custom_Action_VIs.Post-Uninstall_VI
