Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$PSModuleAutoLoadingPreference = 'None'
#Requires -Version 7.0

<#
.SYNOPSIS
    Validates VIPM provider comparison telemetry.

.DESCRIPTION
    Loads the aggregated JSON generated by Invoke-ProviderComparison and ensures
    that all recorded scenarios completed with an acceptable status.  Failing
    entries are surfaced with a descriptive error so CI or local checks can flag
    regressions quickly.

.PARAMETER InputPath
    Path to the telemetry JSON file. Defaults to
    tests/results/_agent/vipm-provider-matrix.json.

.PARAMETER AllowStatuses
    Status values considered successful. Defaults to @('success').

.PARAMETER TreatMissingAsWarning
    When set, missing telemetry results in a warning rather than an error.

.OUTPUTS
    Array of telemetry objects that match the allowed statuses. If failures are
    detected the script throws.

.EXAMPLE
    pwsh -File tools/Vipm/Test-ProviderTelemetry.ps1

    Validates the default telemetry file, throwing if any scenario/provider pair
    reported a non-success status.
#>

[CmdletBinding()]
param(
    [string]$InputPath = 'tests/results/_agent/vipm-provider-matrix.json',
    [string[]]$AllowStatuses = @('success'),
    [switch]$TreatMissingAsWarning
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $InputPath -PathType Leaf)) {
    $message = "VIPM provider telemetry not found at '$InputPath'."
    if ($TreatMissingAsWarning) {
        Write-Warning $message
        return @()
    }
    throw $message
}

$raw = Get-Content -LiteralPath $InputPath -Raw
if (-not $raw) {
    throw "Telemetry file '$InputPath' is empty."
}

try {
    $entries = $raw | ConvertFrom-Json -Depth 8
} catch {
    throw "Failed to parse telemetry JSON at '$InputPath': $($_.Exception.Message)"
}

if ($entries -isnot [System.Collections.IEnumerable]) {
    $entries = @($entries)
}

$failures = $entries | Where-Object { $_.status -and ($_.status -notin $AllowStatuses) }
$failureCount = ($failures | Measure-Object).Count

if ($failureCount -gt 0) {
    $failureSummary = $failures | ForEach-Object {
        "{0} via {1} -> {2} ({3})" -f ($_.scenario ?? '<unknown>'), ($_.provider ?? '<unknown>'), $_.status, ($_.error ?? 'no error detail')
    }
    $message = @(
        'VIPM provider telemetry contains failures:'
        ($failureSummary -join [Environment]::NewLine)
    ) -join [Environment]::NewLine
    throw $message
}

Write-Host ("VIPM provider telemetry validated: {0} entries, statuses {1}." -f $entries.Count, ($AllowStatuses -join ', ')) -ForegroundColor Green

return $entries

function Test-ValidLabel {
  param([Parameter(Mandatory)][string]$Label)
  if ($Label -notmatch '^[A-Za-z0-9._-]{1,64}$') { throw "Invalid label: $Label" }
}

function Invoke-WithTimeout {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory)][scriptblock]$ScriptBlock,
    [Parameter()][int]$TimeoutSec = 600
  )
  $job = Start-Job -ScriptBlock $ScriptBlock
  if (-not (Wait-Job $job -Timeout $TimeoutSec)) {
    try { Stop-Job $job -Force } catch {}
    throw "Operation timed out in $TimeoutSec s"
  }
  Receive-Job $job -ErrorAction Stop
}