#Requires -Version 7.0
[CmdletBinding()]
param(
    [string]$RepoRoot,
    [string]$WorkRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoResolved = if ($RepoRoot) {
    (Resolve-Path -LiteralPath $RepoRoot -ErrorAction Stop).ProviderPath
} else {
    (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..' '..') -ErrorAction Stop).ProviderPath
}

$workResolved = if ($WorkRoot) {
    (Resolve-Path -LiteralPath $WorkRoot -ErrorAction Stop).ProviderPath
} else {
    $defaultPath = Join-Path $repoResolved '.tmp-tests' 'validation' 'seed-cli'
    if (-not (Test-Path -LiteralPath $defaultPath -PathType Container)) {
        New-Item -ItemType Directory -Path $defaultPath -Force | Out-Null
    }
    $defaultPath
}

function Get-SeedRuntimeIdentifier {
    if ([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Windows)) {
        return 'win-x64'
    }
    elseif ([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Linux)) {
        return 'linux-x64'
    }
    else {
        throw "Unsupported OS platform for seed runtime: $([System.Runtime.InteropServices.RuntimeInformation]::OSDescription)"
    }
}

$runtimeIdentifier = Get-SeedRuntimeIdentifier
$publishRoot = Join-Path $workResolved ("publish-{0}" -f $runtimeIdentifier)
if (-not (Test-Path -LiteralPath $publishRoot -PathType Container)) {
    New-Item -ItemType Directory -Path $publishRoot -Force | Out-Null
}

$projectPath = Join-Path $repoResolved 'tools' 'seed-2.2.1' 'src' 'VipbJsonTool' 'VipbJsonTool.csproj'
if (-not (Test-Path -LiteralPath $projectPath -PathType Leaf)) {
    throw "Seed VipbJsonTool project not found at '$projectPath'."
}

Write-Host ("[seed-cli] Publishing VipbJsonTool for {0}" -f $runtimeIdentifier)
dotnet publish $projectPath `
    -c Release `
    -r $runtimeIdentifier `
    --self-contained true `
    -p:PublishSingleFile=true `
    -o $publishRoot `
    | Out-Null

$binaryName = if ($runtimeIdentifier -like 'win-*') { 'VipbJsonTool.exe' } else { 'VipbJsonTool' }
$binaryPath = Join-Path $publishRoot $binaryName
if (-not (Test-Path -LiteralPath $binaryPath -PathType Leaf)) {
    throw "Published VipbJsonTool binary not found at '$binaryPath'."
}

$caseRoot = Join-Path $workResolved 'roundtrip'
if (-not (Test-Path -LiteralPath $caseRoot -PathType Container)) {
    New-Item -ItemType Directory -Path $caseRoot -Force | Out-Null
}

$specJsonPath = Join-Path $caseRoot 'seed.json'
$vipbPath = Join-Path $caseRoot 'seed.vipb'
$roundTripPath = Join-Path $caseRoot 'seed.roundtrip.json'

$seedJson = @'
{
  "Package": {
    "@Version": "2024.0",
    "Package_General_Settings": {
      "Package_File_Name": "IconEditorLab.Seed",
      "Package_Version": "1.2.3.4",
      "Package_Company_Name": "icon-editor-lab",
      "Package_Description": "Sanity payload generated by Test-SeedVipbRoundTrip.ps1."
    },
    "Package_Dependencies": {
      "Dependency": []
    }
  }
}
'@

Set-Content -LiteralPath $specJsonPath -Value $seedJson -Encoding UTF8

Write-Host "[seed-cli] Converting JSON -> VIPB"
& $binaryPath json2vipb $specJsonPath $vipbPath | Write-Host

if (-not (Test-Path -LiteralPath $vipbPath -PathType Leaf)) {
    throw "Seed CLI did not produce '$vipbPath'."
}

Write-Host "[seed-cli] Converting VIPB -> JSON"
& $binaryPath vipb2json $vipbPath $roundTripPath | Write-Host

if (-not (Test-Path -LiteralPath $roundTripPath -PathType Leaf)) {
    throw "Seed CLI did not produce '$roundTripPath'."
}

$original = Get-Content -LiteralPath $specJsonPath -Raw | ConvertFrom-Json -Depth 8
$roundTrip = Get-Content -LiteralPath $roundTripPath -Raw | ConvertFrom-Json -Depth 8

function Assert-EqualValue {
    param(
        [string]$Label,
        $Expected,
        $Actual
    )
    if ($Expected -ne $Actual) {
        throw "Seed CLI round-trip mismatch for '$Label'. Expected '$Expected' but found '$Actual'."
    }
}

Assert-EqualValue -Label 'Package.FileName' `
    -Expected $original.Package.Package_General_Settings.Package_File_Name `
    -Actual $roundTrip.Package.Package_General_Settings.Package_File_Name

Assert-EqualValue -Label 'Package.Version' `
    -Expected $original.Package.Package_General_Settings.Package_Version `
    -Actual $roundTrip.Package.Package_General_Settings.Package_Version

Assert-EqualValue -Label 'Package.Company' `
    -Expected $original.Package.Package_General_Settings.Package_Company_Name `
    -Actual $roundTrip.Package.Package_General_Settings.Package_Company_Name

Write-Host "[seed-cli] VipbJsonTool round-trip validation succeeded."
