param(
    [string]$FixturePath,
    [string]$ResultsRoot,
    [string]$OutputPath,
    [switch]$KeepWork,
    [switch]$SkipResourceOverlay,
    [string]$ResourceOverlayRoot
)
if ([string]::IsNullOrWhiteSpace($FixturePath)) {
    throw 'FixturePath is required; supply the VIP generated by the build.'
}
if (-not (Test-Path 'variable:Global:InvokeValidateLocalStubLog')) {
    $Global:InvokeValidateLocalStubLog = @()
} elseif (-not $Global:InvokeValidateLocalStubLog) {
    $Global:InvokeValidateLocalStubLog = @()
}
$Global:InvokeValidateLocalStubLog += [pscustomobject]@{
    Command = 'Describe'
    Parameters = [pscustomobject]@{
        FixturePath        = $FixturePath
        ResultsRoot        = $ResultsRoot
        SkipResourceOverlay= $SkipResourceOverlay.IsPresent
        ResourceOverlayRoot= $ResourceOverlayRoot
    }
}
if ($OutputPath) {
    $dir = Split-Path -Parent $OutputPath
    if ($dir -and -not (Test-Path -LiteralPath $dir -PathType Container)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}
$summary = [pscustomobject]@{
    schema            = 'icon-editor/fixture-report@v1'
    fixtureOnlyAssets = @()
    artifacts         = @()
    manifest          = [pscustomobject]@{
        packageSmoke = [pscustomobject]@{ status = 'ok'; vipCount = 0 }
        simulation   = [pscustomobject]@{ enabled = $true }
        unitTestsRun = $false
    }
    runnerDependencies = $null
    stakeholder        = $null
    source            = [pscustomobject]@{ fixturePath = $FixturePath }
}
# Populate minimal placeholder data so downstream renderers have structured content
$fixtureArtifact = [pscustomobject]@{
    name      = if ($FixturePath) { Split-Path -Path $FixturePath -Leaf } else { 'fixture.vip' }
    path      = $FixturePath
    kind      = 'vip'
    sizeBytes = (Get-Item -LiteralPath $FixturePath -ErrorAction SilentlyContinue)?.Length ?? 0
    hash      = 'stub-hash'
}
$summary.artifacts = @($fixtureArtifact)
$summary.fixtureOnlyAssets = @(
    [pscustomobject]@{
        category  = 'resource'
        name      = 'StubResource.vi'
        hash      = 'stub-resource-hash'
        sizeBytes = 0
    }
)
$summary.runnerDependencies = [pscustomobject]@{
    fixture    = 'Tooling/deployment/runner_dependencies.vipc'
    hashMatch  = $true
}
$summary.stakeholder = [pscustomobject]@{
    generatedAt        = (Get-Date).ToString('o')
    smokeStatus        = 'ok'
    runnerDependencies = [pscustomobject]@{ matchesRepo = $true }
    customActions      = @()
    fixtureOnlyAssets  = $summary.fixtureOnlyAssets
    artifacts          = $summary.artifacts
}
if ($OutputPath) {
    $json = $summary | ConvertTo-Json -Depth 6
    Set-Content -LiteralPath $OutputPath -Value $json -Encoding utf8
}
$summary
