#Requires -Version 7.0

param(
  [string]$FixturePath,
  [string]$ManifestPath,
  [string]$ResultsRoot,
  [string]$ResourceOverlayRoot,
  [switch]$SkipDocUpdate,     # retained for backward compatibility (no-op)
  [switch]$CheckOnly,         # retained for backward compatibility (no-op)
  [switch]$NoSummary          # retained for backward compatibility (no-op)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Resolve-RepoRoot {
  param([string]$StartPath = (Get-Location).Path)
  try { (git -C $StartPath rev-parse --show-toplevel 2>$null).Trim() } catch { $StartPath }
}

if ($CheckOnly.IsPresent) {
  Write-Warning '-CheckOnly is deprecated and has no effect now that fixture reports are transient.'
}
if ($SkipDocUpdate.IsPresent) {
  Write-Verbose '-SkipDocUpdate specified; documentation updates are no longer performed by this helper.'
}

$repoRoot = Resolve-RepoRoot
$describeScript = Join-Path $repoRoot 'tools/icon-editor/Describe-IconEditorFixture.ps1'
if (-not (Test-Path -LiteralPath $describeScript -PathType Leaf)) {
  throw "Descriptor script not found at '$describeScript'."
}

if (-not $FixturePath) {
  throw 'FixturePath is required; supply the VIP generated by the build.'
}
if (-not (Test-Path -LiteralPath $FixturePath -PathType Leaf)) {
  throw "Fixture VIP not found at '$FixturePath'."
}

$resultsRootResolved = if ($ResultsRoot) {
  if ([System.IO.Path]::IsPathRooted($ResultsRoot)) { $ResultsRoot } else { Join-Path $repoRoot $ResultsRoot }
} else {
  Join-Path $repoRoot 'tests/results/_agent/icon-editor'
}
if (-not (Test-Path -LiteralPath $resultsRootResolved -PathType Container)) {
  New-Item -ItemType Directory -Path $resultsRootResolved -Force | Out-Null
}

$reportPath = Join-Path $resultsRootResolved 'fixture-report.json'
$overlayResolved = $null
if ($ResourceOverlayRoot) {
  $overlayResolved = if ([System.IO.Path]::IsPathRooted($ResourceOverlayRoot)) {
    $ResourceOverlayRoot
  } else {
    Join-Path $repoRoot $ResourceOverlayRoot
  }
  if (-not (Test-Path -LiteralPath $overlayResolved -PathType Container)) {
    throw "Resource overlay path not found at '$overlayResolved'."
  }
  $overlayResolved = (Resolve-Path -LiteralPath $overlayResolved).Path
}

$describeParams = @{
  FixturePath = $FixturePath
  ResultsRoot = (Join-Path $resultsRootResolved '__describe')
  OutputPath  = $reportPath
  KeepWork    = $false
}
if ($overlayResolved) {
  $describeParams['ResourceOverlayRoot'] = $overlayResolved
} else {
  $describeParams['SkipResourceOverlay'] = $true
}

pwsh -NoLogo -NoProfile -File $describeScript @describeParams | Out-Null
$summary = Get-Content -LiteralPath $reportPath -Raw | ConvertFrom-Json -Depth 8

if ($ManifestPath) {
  $manifestEntries = @()
  foreach ($asset in ($summary.fixtureOnlyAssets | Sort-Object category, name)) {
    $rel = switch ($asset.category) {
      'script'   { Join-Path 'scripts' $asset.name }
      'test'     { Join-Path 'tests' $asset.name }
      'resource' { Join-Path 'resource' $asset.name }
      default    { Join-Path $asset.category $asset.name }
    }
    $manifestEntries += [ordered]@{
      key       = ($asset.category + ':' + $rel).ToLower()
      category  = $asset.category
      path      = $rel
      sizeBytes = ($asset.sizeBytes ?? 0)
      hash      = $asset.hash
    }
  }

  $manifestObject = [ordered]@{
    schema      = 'icon-editor/fixture-manifest@v1'
    generatedAt = (Get-Date).ToString('o')
    entries     = $manifestEntries
  }

  $manifestDir = Split-Path -Parent $ManifestPath
  if (-not (Test-Path -LiteralPath $manifestDir -PathType Container)) {
    New-Item -ItemType Directory -Path $manifestDir -Force | Out-Null
  }
  $manifestObject | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $ManifestPath -Encoding utf8
}

if ($NoSummary.IsPresent) {
  return
}

return [pscustomobject]$summary
