<#!
.SYNOPSIS
Generate markdown documentation for composite action inputs & outputs.

.DESCRIPTION
Uses built-in ConvertFrom-Yaml (PowerShell 7+) to parse action.yml and emit
`docs/action-outputs.md`. Safe to run locally or in CI.
#>
[CmdletBinding()]
param(
  [Parameter()][string]$ActionPath = (Join-Path $PSScriptRoot '..' 'action.yml'),
  [Parameter()][string]$OutputPath = (Join-Path $PSScriptRoot '..' 'docs' 'action-outputs.md')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not (Get-Command ConvertFrom-Yaml -ErrorAction SilentlyContinue)) {
  Write-Error 'ConvertFrom-Yaml not available in this PowerShell version.'
  exit 1
}
if (-not (Test-Path -LiteralPath $ActionPath -PathType Leaf)) { Write-Error "action.yml not found: $ActionPath"; exit 1 }

$yaml = Get-Content -LiteralPath $ActionPath -Raw -Encoding UTF8 | ConvertFrom-Yaml

$md = @()
$md += '# Compare VI Action: Inputs & Outputs'
$md += ''
$md += 'Generated by `tools/Generate-ActionOutputsDoc.ps1` (do not edit manually).'
$md += ''

if ($yaml.inputs) {
  $md += '## Inputs'
  $md += ''
  foreach ($prop in ($yaml.inputs.PSObject.Properties | Sort-Object Name)) {
    $name = $prop.Name
    $data = $prop.Value
    $md += "### $name"
    if ($data.description) { $md += $data.description }
    if ($data.required)    { $md += "- Required: $($data.required)" }
    if ($data.default)     { $md += "- Default: `$($data.default)`" }
    $md += ''
  }
}

if ($yaml.outputs) {
  $md += '## Outputs'
  $md += ''
  foreach ($prop in ($yaml.outputs.PSObject.Properties | Sort-Object Name)) {
    $name = $prop.Name
    $data = $prop.Value
    $md += "### $name"
    if ($data.description) { $md += $data.description }
    $md += ''
  }
}

$destDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $destDir -PathType Container)) { New-Item -ItemType Directory -Force -Path $destDir | Out-Null }
$md -join [Environment]::NewLine | Out-File -FilePath $OutputPath -Encoding UTF8
Write-Host "Generated: $OutputPath" -ForegroundColor Green
